name: optimalpH
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - pytorch
  - cudatoolkit
  - biopython
  - fire
  - pip
  - pip:
    - huggingface_hub
    - fair-esm==2.0.0
    - fairscale==0.4.13
    - fsspec
