name: optimalpH
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - pytorch
  - torchvision
  - tqdm
  - requests
  - pyyaml
  - biopython
  - pip
  - pip:
    - fair-esm==2.0.0
    - fairscale==0.4.13
    - fsspec==2024.2.0
    - fire
